// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezyhoftmssizinfwwwdx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6eWhvZnRtc3NpemluZnd3d2R4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MzgwODksImV4cCI6MjA3NDIxNDA4OX0.I7mYui-gz3QXstLk2oFI8zkI86TUI90kV1rw5FVbZPo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});